"use client";
import { useEffect, useState } from "react";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { Container } from "@/components/ui/Container";

interface CycleEntry {
  cycleNumber: number;
  timestamp: string;
  btcPrice: number | null;
  settledOracleIds: string[];
  redeemedDigests: string[];
  hedgeTriggered: boolean;
  deployedToPlp: boolean;
  hedgeBoughtDigest: string | null;
  hedgeStrike: number | null;
  hedgeAskPct: number | null;
  hedgeIsAtm: boolean | null;
  testNote: string | null;
  depositDigests: string[];
  rlDepositDigests: string[];
  totalTxThisSession: number;
  error: string | null;
}

function formatPrice(price: number | null): string {
  if (price === null) return "--";
  return "$" + price.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

function DigestLink({ digest }: { digest: string }) {
  return (
    <a
      href={`https://suiscan.xyz/testnet/tx/${digest}`}
      target="_blank"
      rel="noopener noreferrer"
      className="font-mono text-xs text-accent underline hover:text-accent-hover"
    >
      {digest.slice(0, 10)}...
    </a>
  );
}

export default function ActivityPage() {
  const [cycles, setCycles] = useState<CycleEntry[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    let cancelled = false;

    async function load() {
      try {
        const res = await fetch("/api/activity");
        const data = await res.json();
        if (!cancelled) {
          setCycles(Array.isArray(data.cycles) ? data.cycles : []);
          setError(data.error ?? null);
          setIsLoading(false);
        }
      } catch (e) {
        if (!cancelled) {
          setError(e instanceof Error ? e.message : "Failed to load activity");
          setIsLoading(false);
        }
      }
    }

    load();
    const id = setInterval(load, 30_000);
    return () => {
      cancelled = true;
      clearInterval(id);
    };
  }, []);

  // Sort by wall-clock time, not cycleNumber — the bot's cycle counter
  // resets to 1 on every restart, so cycleNumber alone doesn't reflect
  // chronological order across restarts.
  const sorted = [...cycles].sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime());
  const totalTx = sorted[0]?.totalTxThisSession ?? 0;
  const totalCycles = cycles.length;
  const totalHedgesSettled = cycles.filter((c) => c.hedgeTriggered).length;

  return (
    <>
      <Header />
      <main>
        <section className="border-b border-border py-16 lg:py-24">
          <Container>
            <p className="font-mono text-xs uppercase tracking-widest text-ink-muted mb-6">Marathon Bot / Activity</p>
            <h1 className="font-display text-5xl lg:text-6xl leading-tight tracking-tight text-ink max-w-3xl">Live cycle feed</h1>
            <p className="mt-4 text-lg leading-relaxed text-ink-secondary max-w-2xl">On-chain transaction history generated by the marathon bot's continuous vault cycles — deposits, PLP deployments, and permissionless hedge settlements.</p>

            <div className="mt-10 flex flex-wrap gap-x-12 gap-y-4">
              <div>
                <p className="font-mono text-xs uppercase tracking-widest text-ink-muted mb-1">Total transactions</p>
                <p className="font-mono text-3xl tabular-nums text-accent">{totalTx}</p>
              </div>
              <div>
                <p className="font-mono text-xs uppercase tracking-widest text-ink-muted mb-1">Cycles logged</p>
                <p className="font-mono text-3xl tabular-nums text-ink">{totalCycles}</p>
              </div>
              <div>
                <p className="font-mono text-xs uppercase tracking-widest text-ink-muted mb-1">Hedges settled</p>
                <p className="font-mono text-3xl tabular-nums text-ink">{totalHedgesSettled}</p>
              </div>
            </div>
          </Container>
        </section>

        <section className="py-16 lg:py-24">
          <Container>
            {isLoading && cycles.length === 0 && (
              <p className="font-mono text-sm text-ink-muted">Loading cycle log...</p>
            )}

            {error && (
              <p className="font-mono text-sm text-negative mb-6">{error}</p>
            )}

            {!isLoading && cycles.length === 0 && !error && (
              <p className="font-mono text-sm text-ink-muted">No cycles logged yet. Run the marathon bot to generate activity.</p>
            )}

            <div className="space-y-4">
              {sorted.map((cycle) => (
                <div key={`${cycle.cycleNumber}-${cycle.timestamp}`} className="border border-border bg-paper-raised p-5">
                  <div className="flex flex-wrap items-center justify-between gap-3 mb-3">
                    <div className="flex items-center gap-4">
                      <span className="font-mono text-sm text-ink">{new Date(cycle.timestamp).toLocaleString()}</span>
                      <span className="font-mono text-xs uppercase tracking-widest text-ink-muted">Cycle {cycle.cycleNumber}</span>
                    </div>
                    <div className="flex items-center gap-3">
                      {cycle.hedgeTriggered && (
                        <span className="font-mono text-xs uppercase tracking-widest text-negative border border-negative px-2 py-0.5">Hedge settled</span>
                      )}
                      {cycle.hedgeBoughtDigest && (
                        <span className="font-mono text-xs uppercase tracking-widest text-accent border border-accent px-2 py-0.5">Hedge bought</span>
                      )}
                      {cycle.deployedToPlp && (
                        <span className="font-mono text-xs uppercase tracking-widest text-positive border border-positive px-2 py-0.5">Deployed to PLP</span>
                      )}
                      {cycle.error && (
                        <span className="font-mono text-xs uppercase tracking-widest text-negative">Error</span>
                      )}
                    </div>
                  </div>

                  <div className="flex flex-wrap items-center gap-x-8 gap-y-2 mb-3">
                    <div className="flex items-center gap-2">
                      <span className="font-mono text-xs uppercase tracking-widest text-ink-muted">BTC</span>
                      <span className="font-mono text-sm tabular-nums text-accent">{formatPrice(cycle.btcPrice)}</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <span className="font-mono text-xs uppercase tracking-widest text-ink-muted">Total tx so far</span>
                      <span className="font-mono text-sm tabular-nums text-ink">{cycle.totalTxThisSession}</span>
                    </div>
                  </div>

                  {(cycle.depositDigests.length > 0 || (cycle.rlDepositDigests?.length ?? 0) > 0 || cycle.redeemedDigests.length > 0 || cycle.hedgeBoughtDigest) && (
                    <div className="flex flex-wrap gap-x-8 gap-y-2 pt-3 border-t border-border">
                      {cycle.depositDigests.length > 0 && (
                        <div className="flex items-center gap-2 flex-wrap">
                          <span className="font-mono text-xs uppercase tracking-widest text-ink-muted">Deposits (STRATA-PH)</span>
                          {cycle.depositDigests.map((d) => <DigestLink key={d} digest={d} />)}
                        </div>
                      )}
                      {(cycle.rlDepositDigests?.length ?? 0) > 0 && (
                        <div className="flex items-center gap-2 flex-wrap">
                          <span className="font-mono text-xs uppercase tracking-widest text-ink-muted">Deposits (STRATA-RL)</span>
                          {cycle.rlDepositDigests.map((d) => <DigestLink key={d} digest={d} />)}
                        </div>
                      )}
                      {cycle.redeemedDigests.length > 0 && (
                        <div className="flex items-center gap-2 flex-wrap">
                          <span className="font-mono text-xs uppercase tracking-widest text-ink-muted">Redeemed</span>
                          {cycle.redeemedDigests.map((d) => <DigestLink key={d} digest={d} />)}
                        </div>
                      )}
                      {cycle.hedgeBoughtDigest && (
                        <div className="flex items-center gap-2 flex-wrap">
                          <span className="font-mono text-xs uppercase tracking-widest text-ink-muted">Hedge bought</span>
                          <DigestLink digest={cycle.hedgeBoughtDigest} />
                          {cycle.hedgeStrike !== null && (
                            <span className="font-mono text-xs text-ink-muted">
                              strike {formatPrice(cycle.hedgeStrike)} — {cycle.hedgeIsAtm ? "ATM" : "OTM"}
                              {cycle.hedgeAskPct !== null && ` (${cycle.hedgeAskPct.toFixed(1)}% prob)`}
                            </span>
                          )}
                        </div>
                      )}
                    </div>
                  )}

                  {cycle.testNote && (
                    <p className="mt-3 font-mono text-xs italic text-ink-muted">⚠ {cycle.testNote}</p>
                  )}

                  {cycle.error && (
                    <p className="mt-3 font-mono text-xs text-negative">{cycle.error}</p>
                  )}
                </div>
              ))}
            </div>
          </Container>
        </section>
      </main>
      <Footer />
    </>
  );
}
